name: Deploy Next Js App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency: 
      group: deploy
      cancel-in-progress: true
   
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      - name: install Dependencies
        run: npm install
      - name: Build Next.JS App
        run:  npm run build
      - name: Deploying App
        run: echo "Deploying App....."
